### ISSUE TITLE
Can't add meson-gxl-s905x-libretech-cc-uarta

### ISSUE THREAD

**Issue by V10lator** [BayLibre/libretech-cc-overlays#3]
Whenever I do `overlay.sh add libretech-cc-uarta` I get:

    meson_uart: probe of c11084c0.serial failed with error -22

in dmesg.

**Comment by superna9999** [comment]
Hi, 

We will investigate this issue

**Comment by superna9999** [comment]
@V10lator Can you try the fix I pushed at https://github.com/BayLibre/libretech-overlays/commit/47f41a0cc25dec8dcd8028064bd558b219cf976d ?

It should solve the issue.

**Comment by V10lator** [comment]
@superna9999 Confirming the fix. Thank you.

**Comment by superna9999** [comment]
Thanks, pushed to this repo
